### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by tu0908** [tencentyun/LiteAVProfessional_Android#2]
demo 直接运行提示错误：
com/tencent/liteav/trtcaudiocalldemo/demo/AudioCallMainActivity.java 
 错误: 找不到符号 符号: 变量 PLACEHOLDER 位置: 类 GenerateTestUserSig

**Comment by carolsuo** [comment]
需要配置 GenerateTestUserSig 中的 sdkappid 和 key
https://cloud.tencent.com/document/product/454/14548#Client

**Comment by baichunqiu** [comment]
配置SDKAPPID和SECRETKEY后，还是报错，可能不是这个问题  希望检查一下是不是项目配置的问题，谢谢。
trtcvoiceroom 缺少一个gson依赖
implementation 'com.google.code.gson:gson:2.8.5'

**Comment by carolsuo** [comment]
按照不同的modeule分别有四个地方需要配置，麻烦您再确认下是不是都配置好了。
如果您只需要trtc相关的demo，可以参考 https://github.com/tencentyun/TRTCSDK/

**Comment by LucasXu01** [comment]
遇到了同样的问题

**Comment by whalehe** [comment]
您好，可以更新到最新版本7.4，如果还有问题，麻烦附上日志信息，或者截图。
