### ISSUE TITLE
8.5.10031 在 targetSdkVersion 30 上，点播播放器还是会崩溃

### ISSUE THREAD

**Issue by limuyang2** [tencentyun/LiteAVProfessional_Android#6]
在 `targetSdkVersion` 为 30 的机型上(也就是 android 11)，使用 `TXVodPlayer` 播放点播视频会直接崩溃。

从 7.9 版本到 8.5 了还不修复？都反馈 N 多次了。就是这么对待付费用户的？？？？

真的想口吐芬芳

**Comment by limuyang2** [comment]
补充下信息：
使用的包如下：
```
implementation (name: 'LiteAVSDK_Professional_8.5.10031', ext: 'aar')
```

targetSdkVersion 29 时，正常。
targetSdkVersion 30 时，崩溃。

**Comment by GodCrypto0616** [comment]
Hello
I face same issues. TXVodPlayer is crashed on android 11.
I wish you fix this issue asap.

**Comment by limuyang2** [comment]
> Hello
> I face same issues. TXVodPlayer is crashed on android 11.
> I wish you fix this issue asap.

8.6 already fixed
